/* Last.json (c) 2012 Sven Over <sven@last.fm>

 Permission is hereby granted, free of charge, to any person or organization
 obtaining a copy of the software and accompanying documentation covered by
 this license (the "Software") to use, reproduce, display, distribute,
 execute, and transmit the Software, and to prepare derivative works of the
 Software, and to permit third-parties to whom the Software is furnished to
 do so, all subject to the following:

 The copyright notices in the Software and this entire statement, including
 the above license grant, this restriction and the following disclaimer,
 must be included in all copies of the Software, in whole or in part, and
 all derivative works of the Software, unless such copies or derivative
 works are solely in the form of machine-executable object code generated by
 a source language processor.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 DEALINGS IN THE SOFTWARE.

*/

#ifndef LASTJSON_EXCEPTIONS_HPP__
#define LASTJSON_EXCEPTIONS_HPP__

#include <string>
#include <stdexcept>

namespace lastjson {

class json_error : public std::runtime_error
{
public:
    json_error(std::string const & arg)
        : std::runtime_error(arg)
    {
    }
};

class type_error : public json_error
{
public:
    type_error(std::string const & arg)
        : json_error(arg)
    {
    }
};

class parser_error : public json_error
{
public:
    parser_error(std::string const & arg)
        : json_error(arg)
    {
    }
};

class utf8_sequence_error : public json_error
{
public:
    utf8_sequence_error(std::string const & arg = "error decoding utf-8 sequence")
        : json_error(arg)
    {
    }
};

class range_error : public json_error
{
public:
    range_error(std::string const & arg)
        : json_error(arg)
    {
    }
};

} // namespace lastjson

#endif // ifndef LASTJSON_EXCEPTIONS_HPP__

